-- SQL CODE (might not work, I had chat gpt create it, but you can try creating a database using this on your end, that way you can ensure the column names are the same as the ones in the code)

-- =========================================================
-- CREATE DATABASE
-- =========================================================
-- CREATE DATABASE foodpantry;
-- \c foodpantry (if using psql)

DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS employees;

-- =========================================================
-- EMPLOYEES TABLE
-- =========================================================
CREATE TABLE employees (
    employee_id INTEGER GENERATED BY DEFAULT AS IDENTITY
        (START WITH 1000 INCREMENT BY 1),
    first_name  VARCHAR(25) NOT NULL,
    last_name   VARCHAR(30) NOT NULL,
    level       VARCHAR(7)  NOT NULL,
    username    VARCHAR(30) NOT NULL,
    password    VARCHAR(30) NOT NULL,
    CONSTRAINT employees_pk PRIMARY KEY (employee_id),
    CONSTRAINT employees_level_chk CHECK (level IN ('Manager', 'Employee'))
);

-- =========================================================
-- CUSTOMERS TABLE
-- =========================================================
CREATE TABLE customers (
    customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY
        (START WITH 10 INCREMENT BY 1),
    first_name  VARCHAR(25) NOT NULL,
    last_name   VARCHAR(30) NOT NULL,
    phone_num   VARCHAR(10) NOT NULL,
    email       VARCHAR(40) NOT NULL,
    location    VARCHAR(15) NOT NULL,
    CONSTRAINT customers_pk PRIMARY KEY (customer_id),
    CONSTRAINT customers_location_chk CHECK
        (location IN ('blanding','salt-lake','st-george','sprinville'))
);

-- =========================================================
-- ORDERS TABLE
-- =========================================================
CREATE TABLE orders (
    order_id    INTEGER GENERATED BY DEFAULT AS IDENTITY
        (START WITH 1000000 INCREMENT BY 1),
    customer_id INTEGER NOT NULL,
    employee_id INTEGER NOT NULL,
    quantity    INTEGER,
    date        DATE,
    CONSTRAINT orders_pk PRIMARY KEY (order_id),
    CONSTRAINT orders_customer_fk FOREIGN KEY (customer_id)
    CONSTRAINT orders_employee_fk FOREIGN KEY (employee_id)
);

-- =========================================================
-- INSERT EMPLOYEES (first 4 from screenshot)
-- =========================================================

INSERT INTO employees (first_name, last_name, level, username, password) VALUES
('Paris', 'Ward', 'Manager', 'pward', 'admin'),
('Lucas', 'Moraes', 'Manager', 'lmoraes', 'admin'),
('Parker', 'Sandstrom', 'Manager', 'psandstrom', 'admin'),
('Josh', 'Ethington', 'Manager', 'jethington', 'admin'),
('Emma','Johnson','Employee','ejohnson','admin'),
('Liam','Brown','Employee','lbrown','admin'),
('Olivia','Davis','Employee','odavis','admin'),
('Noah','Miller','Employee','nmiller','admin'),
('Ava','Wilson','Employee','awilson','admin'),
('William','Moore','Employee','wmoore','admin'),
('Sophia','Taylor','Employee','staylor','admin'),
('James','Anderson','Employee','janderson','admin'),
('Isabella','Thomas','Employee','ithomas','admin'),
('Benjamin','Jackson','Employee','bjackson','admin'),
('Mia','White','Employee','mwhite','admin'),
('Elijah','Harris','Employee','eharris','admin'),
('Charlotte','Martin','Employee','cmartin','admin'),
('Henry','Thompson','Employee','hthompson','admin'),
('Amelia','Garcia','Employee','agarcia','admin'),
('Alexander','Martinez','Employee','amartinez','admin'),
('Harper','Robinson','Employee','hrobinson','admin'),
('Daniel','Clark','Employee','dclark','admin'),
('Evelyn','Rodriguez','Employee','erodriguez','admin'),
('Michael','Lewis','Employee','mlewis','admin'),
('Abigail','Lee','Employee','alee','admin'),
('Ethan','Walker','Employee','ewalker','admin'),
('Emily','Hall','Employee','ehall','admin'),
('Jacob','Allen','Employee','jallen','admin'),
('Elizabeth','Young','Employee','eyoung','admin'),
('David','Hernandez','Employee','dhernandez','admin');

-- =========================================================
-- INSERT 50 CUSTOMERS (named)
-- =========================================================

INSERT INTO customers (first_name, last_name, phone_num, email, location) VALUES
('Sarah','Carter','3855550101','sarah.carter@example.com','blanding'),
('John','Phillips','8015550102','john.phillips@example.com','salt-lake'),
('Megan','Lopez','4355550103','megan.lopez@example.com','st-george'),
('Ryan','Turner','3855550104','ryan.turner@example.com','sprinville'),
('Chloe','Mitchell','8015550105','chloe.mitchell@example.com','blanding'),
('Brandon','Morris','3855550106','brandon.morris@example.com','salt-lake'),
('Katie','Nguyen','4355550107','katie.nguyen@example.com','st-george'),
('Tyler','Price','8015550108','tyler.price@example.com','sprinville'),
('Ashley','Rivera','3855550109','ashley.rivera@example.com','blanding'),
('Justin','Brooks','8015550110','justin.brooks@example.com','salt-lake'),
('Hannah','Cook','4355550111','hannah.cook@example.com','st-george'),
('Logan','Reed','3855550112','logan.reed@example.com','sprinville'),
('Natalie','Gray','8015550113','natalie.gray@example.com','blanding'),
('Aaron','Foster','3855550114','aaron.foster@example.com','salt-lake'),
('Madison','Hughes','4355550115','madison.hughes@example.com','st-george'),
('Dylan','Butler','8015550116','dylan.butler@example.com','sprinville'),
('Zoe','Simmons','3855550117','zoe.simmons@example.com','blanding'),
('Gavin','Bryant','4355550118','gavin.bryant@example.com','salt-lake'),
('Lily','Sanders','8015550119','lily.sanders@example.com','st-george'),
('Jason','Ramirez','3855550120','jason.ramirez@example.com','sprinville'),
('Ella','Ward','4355550121','ella.ward@example.com','blanding'),
('Blake','Cooper','8015550122','blake.cooper@example.com','salt-lake'),
('Lauren','Parker','3855550123','lauren.parker@example.com','st-george'),
('Colin','Stewart','4355550124','colin.stewart@example.com','sprinville'),
('Paige','West','8015550125','paige.west@example.com','blanding'),
('Trevor','Stone','3855550126','trevor.stone@example.com','salt-lake'),
('Julia','Richards','4355550127','julia.richards@example.com','st-george'),
('Aiden','Knight','8015550128','aiden.knight@example.com','sprinville'),
('Brooke','Hayes','3855550129','brooke.hayes@example.com','blanding'),
('Mason','Graham','4355550130','mason.graham@example.com','salt-lake'),
('Claire','Gibson','8015550131','claire.gibson@example.com','st-george'),
('Carter','Barnes','3855550132','carter.barnes@example.com','sprinville'),
('Haley','Ford','8015550133','haley.ford@example.com','blanding'),
('Austin','Walsh','3855550134','austin.walsh@example.com','salt-lake'),
('Faith','Boyd','4355550135','faith.boyd@example.com','st-george'),
('Marcus','Lowe','8015550136','marcus.lowe@example.com','sprinville'),
('Piper','Dean','3855550137','piper.dean@example.com','blanding'),
('Julian','Cross','8015550138','julian.cross@example.com','salt-lake'),
('Kayla','Barber','4355550139','kayla.barber@example.com','st-george'),
('Seth','Willis','8015550140','seth.willis@example.com','sprinville'),
('Violet','Briggs','3855550141','violet.briggs@example.com','blanding'),
('Owen','Harmon','4355550142','owen.harmon@example.com','salt-lake'),
('Stella','Swanson','8015550143','stella.swanson@example.com','st-george'),
('Chase','McCoy','3855550144','chase.mccoy@example.com','sprinville'),
('Nora','Erickson','8015550145','nora.erickson@example.com','blanding'),
('Wyatt','Chandler','3855550146','wyatt.chandler@example.com','salt-lake'),
('Ruby','Holt','4355550147','ruby.holt@example.com','st-george'),
('Cameron','Webb','8015550148','cameron.webb@example.com','sprinville'),
('Elise','Pratt','3855550149','elise.pratt@example.com','blanding'),
('Joel','Whitaker','4355550150','joel.whitaker@example.com','salt-lake');

-- =========================================================
-- INSERT 100 ORDERS (auto-generated)
-- =========================================================

INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (12, 1003, 4, '2024-01-03');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (27, 1014, 2, '2024-01-04');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (33, 1021, 6, '2024-01-05');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (41, 1007, 3, '2024-01-06');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (18, 1011, 1, '2024-01-06');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (49, 1002, 5, '2024-01-07');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (23, 1025, 2, '2024-01-08');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (31, 1009, 7, '2024-01-08');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (55, 1018, 3, '2024-01-09');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (14, 1004, 4, '2024-01-10');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (36, 1027, 8, '2024-01-11');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (59, 1022, 3, '2024-01-11');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (25, 1013, 1, '2024-01-12');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (47, 1016, 6, '2024-01-12');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (11, 1005, 2, '2024-01-13');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (30, 1020, 4, '2024-01-13');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (44, 1010, 9, '2024-01-13');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (50, 1008, 3, '2024-01-14');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (15, 1029, 5, '2024-01-14');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (22, 1019, 2, '2024-01-15');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (37, 1001, 4, '2024-01-15');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (43, 1024, 7, '2024-01-16');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (56, 1012, 3, '2024-01-16');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (19, 1000, 5, '2024-01-17');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (32, 1028, 2, '2024-01-17');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (45, 1017, 1, '2024-01-18');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (13, 1015, 4, '2024-01-18');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (58, 1023, 3, '2024-01-19');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (29, 1006, 6, '2024-01-19');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (16, 1003, 2, '2024-01-20');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (42, 1026, 7, '2024-01-20');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (51, 1002, 3, '2024-01-21');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (24, 1001, 5, '2024-01-21');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (35, 1018, 2, '2024-01-22');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (48, 1029, 4, '2024-01-22');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (17, 1014, 1, '2024-01-23');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (40, 1007, 9, '2024-01-23');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (52, 1010, 6, '2024-01-24');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (21, 1009, 3, '2024-01-24');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (38, 1021, 8, '2024-01-25');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (53, 1013, 2, '2024-01-25');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (26, 1027, 7, '2024-01-26');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (54, 1022, 3, '2024-01-26');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (28, 1011, 1, '2024-01-27');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (46, 1016, 5, '2024-01-27');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (20, 1004, 4, '2024-01-28');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (34, 1020, 6, '2024-01-28');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (57, 1008, 3, '2024-01-28');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (10, 1005, 2, '2024-01-29');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (39, 1024, 7, '2024-01-29');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (58, 1012, 4, '2024-02-01');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (41, 1003, 5, '2024-02-01');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (15, 1017, 3, '2024-02-02');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (22, 1019, 2, '2024-02-02');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (31, 1028, 8, '2024-02-03');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (50, 1001, 4, '2024-02-03');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (44, 1025, 9, '2024-02-04');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (12, 1000, 1, '2024-02-04');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (33, 1014, 6, '2024-02-05');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (56, 1026, 3, '2024-02-05');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (27, 1008, 4, '2024-02-06');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (17, 1011, 2, '2024-02-06');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (43, 1023, 7, '2024-02-07');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (36, 1006, 3, '2024-02-07');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (55, 1018, 1, '2024-02-08');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (14, 1004, 5, '2024-02-08');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (28, 1022, 2, '2024-02-09');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (53, 1021, 6, '2024-02-09');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (49, 1029, 8, '2024-02-10');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (35, 1015, 3, '2024-02-10');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (30, 1024, 7, '2024-02-11');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (21, 1002, 4, '2024-02-11');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (59, 1009, 3, '2024-02-12');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (18, 1016, 2, '2024-02-12');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (46, 1010, 5, '2024-02-13');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (41, 1017, 9, '2024-02-13');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (29, 1028, 6, '2024-02-14');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (12, 1026, 1, '2024-02-14');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (48, 1001, 7, '2024-02-15');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (57, 1027, 4, '2024-02-15');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (10, 1020, 3, '2024-02-16');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (24, 1007, 5, '2024-02-16');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (34, 1025, 8, '2024-02-17');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (52, 1023, 2, '2024-02-17');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (11, 1019, 4, '2024-02-18');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (37, 1003, 6, '2024-02-18');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (20, 1021, 7, '2024-02-19');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (50, 1012, 1, '2024-02-19');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (15, 1013, 3, '2024-02-20');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (45, 1029, 6, '2024-02-20');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (22, 1005, 2, '2024-02-21');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (33, 1024, 8, '2024-02-21');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (56, 1009, 1, '2024-02-22');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (27, 1018, 5, '2024-02-22');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (58, 1006, 3, '2024-02-23');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (43, 1026, 9, '2024-02-23');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (14, 1015, 4, '2024-02-24');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (32, 1008, 6, '2024-02-24');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (48, 1027, 3, '2024-02-25');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (18, 1016, 7, '2024-02-25');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (51, 1004, 5, '2024-02-26');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (29, 1011, 2, '2024-02-26');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (44, 1028, 8, '2024-02-27');
INSERT INTO orders (customer_id, employee_id, quantity, date) VALUES (16, 1002, 3, '2024-02-27');
